import type { DeviceContact } from '@/components/Chat-extended/interfaces';

export const mockContacts: DeviceContact[] = [
  {
    id: 'user-101',
    displayName: 'Sabrina Mattioli',
    initials: 'SM',
    phoneNumber: '+39 320 111 9271',
    avatarColor: '#f97316',
    statusMessage: 'Living my best food blog life',
    tags: ['Family'],
    isFavorite: true,
  },
  {
    id: 'user-102',
    displayName: 'Denis Bassani',
    initials: 'DB',
    phoneNumber: '+39 351 202 8844',
    avatarColor: '#6366f1',
    statusMessage: 'Retro gaming enthusiast',
    tags: ['Friends'],
    lastInteractionAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    id: 'user-103',
    displayName: 'Sabrina "Sab"',
    initials: 'S',
    phoneNumber: '+39 347 980 4411',
    avatarColor: '#ec4899',
    statusMessage: "Currently in Val d'Aosta",
    tags: ['Travel'],
  },
  {
    id: 'user-104',
    displayName: 'Mirko Caruccio',
    initials: 'MC',
    phoneNumber: '+39 392 183 1120',
    avatarColor: '#0ea5e9',
    statusMessage: 'Marvel Snap strategies unlocked',
    tags: ['Gaming'],
  },
  {
    id: 'user-105',
    displayName: 'Sab Enzo Fra Anto',
    initials: 'SE',
    phoneNumber: '+39 392 554 7272',
    avatarColor: '#10b981',
    statusMessage: 'Squad goals',
    tags: ['Friends'],
    isFavorite: true,
  },
  {
    id: 'user-106',
    displayName: 'Luca Meneghin',
    initials: 'LM',
    phoneNumber: '+39 333 555 0190',
    avatarColor: '#22c55e',
    statusMessage: 'Always exploring new builds',
    tags: ['Me'],
  },
  {
    id: 'user-107',
    displayName: 'Meta AI',
    initials: 'AI',
    phoneNumber: '+1 415 555 1000',
    avatarColor: '#6366f1',
    statusMessage: 'How can I help you today?',
    tags: ['Work'],
  },
  {
    id: 'user-108',
    displayName: 'Blizzard Squad',
    initials: 'BS',
    phoneNumber: '+39 351 543 1299',
    avatarColor: '#ef4444',
    statusMessage: 'Seasonal raids incoming',
    tags: ['Gaming'],
  },
];
